                                                                                                                                                                                                                                                                                                                                                                                                                    -- Addiction Control App Database Schema
                                                                                                                                                                                                                                                                                                                                                                                                                    -- Run this SQL in your Supabase SQL Editor to set up the database

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Enable Row Level Security
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE auth.users ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create profiles table
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE profiles (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID REFERENCES auth.users(id) PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      username TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      bio TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      goals TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      privacy_level TEXT DEFAULT 'public' CHECK (privacy_level IN ('public', 'private')),
                                                                                                                                                                                                                                                                                                                                                                                                                      avatar_url TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create habits table
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE habits (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      name TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      description TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create habit_logs table
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE habit_logs (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      habit_id UUID REFERENCES habits(id) ON DELETE CASCADE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      date DATE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      value INTEGER DEFAULT 0, -- 0 = failure, 1 = success, can be used for quantities too
                                                                                                                                                                                                                                                                                                                                                                                                                      note TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      UNIQUE(habit_id, date)
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create daily_goals table
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE daily_goals (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      date DATE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      goal_text TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      is_done BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      UNIQUE(user_id, date)
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create resources table
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE resources (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      title TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      description TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      url TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      category TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      type TEXT DEFAULT 'article' CHECK (type IN ('article', 'video', 'tool', 'book')),
                                                                                                                                                                                                                                                                                                                                                                                                                      author TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      read_time TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      featured BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create badges table
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE badges (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      name TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      description TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      criteria TEXT, -- Description of how to earn this badge
                                                                                                                                                                                                                                                                                                                                                                                                                      icon TEXT, -- Icon name or URL
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create user_badges table (many-to-many relationship)
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE user_badges (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      badge_id UUID REFERENCES badges(id) ON DELETE CASCADE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      awarded_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      UNIQUE(user_id, badge_id)
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create messages table for community chat
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE messages (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      room TEXT DEFAULT 'general' NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      content TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create tips table for storing AI-generated or custom tips
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TABLE tips (
                                                                                                                                                                                                                                                                                                                                                                                                                      id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                                                                                                                                      user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
                                                                                                                                                                                                                                                                                                                                                                                                                      content TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                                                                                                                                      category TEXT,
                                                                                                                                                                                                                                                                                                                                                                                                                      is_ai_generated BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                                                                                                                                                      created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                                                                                                                                                                                                                                                                                                                                                                                                                    );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Enable Row Level Security on all tables
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE habits ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE habit_logs ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE daily_goals ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE badges ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE user_badges ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE messages ENABLE ROW LEVEL SECURITY;
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER TABLE tips ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create RLS policies

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Profiles policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can view their own profile" ON profiles
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR SELECT USING (auth.uid() = id);

                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can insert their own profile" ON profiles
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR INSERT WITH CHECK (auth.uid() = id);

                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can update their own profile" ON profiles
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR UPDATE USING (auth.uid() = id);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Habits policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can manage their own habits" ON habits
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR ALL USING (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Habit logs policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can manage logs for their habits" ON habit_logs
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR ALL USING (
                                                                                                                                                                                                                                                                                                                                                                                                                        EXISTS (
                                                                                                                                                                                                                                                                                                                                                                                                                          SELECT 1 FROM habits 
                                                                                                                                                                                                                                                                                                                                                                                                                          WHERE habits.id = habit_logs.habit_id 
                                                                                                                                                                                                                                                                                                                                                                                                                          AND habits.user_id = auth.uid()
                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                      );

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Daily goals policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can manage their own daily goals" ON daily_goals
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR ALL USING (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Resources policies (public read, admin write)
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Anyone can read resources" ON resources
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR SELECT USING (TRUE);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Badges policies (public read)
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Anyone can read badges" ON badges
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR SELECT USING (TRUE);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- User badges policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can view their own badges" ON user_badges
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR SELECT USING (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can earn badges" ON user_badges
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR INSERT WITH CHECK (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Messages policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can read messages in their rooms" ON messages
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR SELECT USING (TRUE); -- Public read for community

                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can send messages" ON messages
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR INSERT WITH CHECK (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Tips policies
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE POLICY "Users can manage their own tips" ON tips
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR ALL USING (auth.uid() = user_id OR user_id IS NULL);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create functions for automatic updated_at timestamps
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE OR REPLACE FUNCTION update_updated_at_column()
                                                                                                                                                                                                                                                                                                                                                                                                                    RETURNS TRIGGER AS $$
                                                                                                                                                                                                                                                                                                                                                                                                                    BEGIN
                                                                                                                                                                                                                                                                                                                                                                                                                      NEW.updated_at = timezone('utc'::text, now());
                                                                                                                                                                                                                                                                                                                                                                                                                      RETURN NEW;
                                                                                                                                                                                                                                                                                                                                                                                                                    END;
                                                                                                                                                                                                                                                                                                                                                                                                                    $$ language 'plpgsql';

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create triggers for updated_at
                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON profiles
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

                                                                                                                                                                                                                                                                                                                                                                                                                    CREATE TRIGGER update_habits_updated_at BEFORE UPDATE ON habits
                                                                                                                                                                                                                                                                                                                                                                                                                      FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Insert some default badges
                                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO badges (name, description, criteria) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                      ('First Step', 'Completed your first day', 'Log your first successful day'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Week Warrior', 'One week streak', 'Maintain a 7-day streak'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Month Master', '30-day streak', 'Maintain a 30-day streak'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Century Champion', '100-day streak', 'Maintain a 100-day streak'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Dedicated Starter', '10 total days', 'Complete 10 successful days total'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Persistent Fighter', '50 total days', 'Complete 50 successful days total'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Community Helper', 'Active in community', 'Send 10 supportive messages'),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Resource Explorer', 'Learning focused', 'Read 5 resources from library');

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Insert some default resources
                                                                                                                                                                                                                                                                                                                                                                                                                    INSERT INTO resources (title, description, category, type, author, read_time, featured) VALUES
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Understanding Addiction: The Science Behind It', 'Learn about the neurological and psychological aspects of addiction and how it affects the brain.', 'education', 'article', 'Dr. Sarah Johnson', '8 min read', TRUE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Mindfulness Meditation for Recovery', 'A comprehensive guide on using mindfulness techniques to support your recovery journey.', 'mindfulness', 'article', 'Mindful Recovery Institute', '15 min read', TRUE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Building a Strong Support Network', 'Practical tips on how to identify, build, and maintain relationships that support your recovery.', 'support', 'article', 'Recovery Community', '6 min read', FALSE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Cognitive Behavioral Therapy Techniques', 'Learn CBT strategies that you can practice daily to change negative thought patterns.', 'therapy', 'article', 'Dr. Michael Chen', '10 min read', FALSE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Nutrition and Recovery: Healing Your Body', 'How proper nutrition can support your physical and mental health during recovery.', 'health', 'article', 'Nutritionist Lisa Park', '7 min read', FALSE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Dealing with Triggers and Cravings', 'Practical strategies for identifying, avoiding, and managing triggers in your daily life.', 'coping', 'article', 'Recovery Experts', '12 min read', TRUE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('The Role of Exercise in Recovery', 'How physical activity can boost mood, reduce stress, and support overall recovery.', 'health', 'article', 'Fitness for Recovery', '5 min read', FALSE),
                                                                                                                                                                                                                                                                                                                                                                                                                      ('Family and Addiction: Healing Together', 'Resources for family members and how to rebuild relationships affected by addiction.', 'support', 'article', 'Family Recovery Center', '9 min read', FALSE);

                                                                                                                                                                                                                                                                                                                                                                                                                    -- Create realtime subscriptions for messages (optional, for real-time chat)
                                                                                                                                                                                                                                                                                                                                                                                                                    -- This enables real-time functionality for the community chat
                                                                                                                                                                                                                                                                                                                                                                                                                    ALTER PUBLICATION supabase_realtime ADD TABLE messages;
