-- Weather logs table for storing basic local weather snapshots tied to a user
-- Run this in your Supabase SQL editor or include in migrations

create table if not exists public.weather_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone default now(),
  condition text,
  description text,
  temp_c numeric,
  city text,
  mood text,
  craving_level int,
  suggestion text
);

-- Helpful index
create index if not exists weather_logs_user_created_idx on public.weather_logs(user_id, created_at desc);

-- RLS: Only allow users to see/insert their own rows
alter table public.weather_logs enable row level security;

create policy weather_logs_insert_self
  on public.weather_logs for insert
  with check (auth.uid() = user_id);

create policy weather_logs_select_self
  on public.weather_logs for select
  using (auth.uid() = user_id);
